# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapsNetworkLayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMapsNetworkLayer

pod 'Moya', '~> 11.0'

  target 'GoogleMapsNetworkLayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoogleMapsNetworkLayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
